---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-daemon
  namespace: default
  labels:
    app: my-daemon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-daemon
  template:
    metadata:
      labels:
        app: my-daemon
    spec:
      containers:
        - name: my-daemon
          image: my-daemon:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
