---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: default
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
